// Code generated by protoc-gen-go. DO NOT EDIT.
// source: changer.proto

/*
Package changer is a generated protocol buffer package.

It is generated from these files:
	changer.proto

It has these top-level messages:
	ManagersRequest
	ManagersReply
	PasswdConfig
	ChangeRequest
	Status
*/
package changer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeRequest_Manager int32

const (
	ChangeRequest_LASTPASS ChangeRequest_Manager = 0
)

var ChangeRequest_Manager_name = map[int32]string{
	0: "LASTPASS",
}
var ChangeRequest_Manager_value = map[string]int32{
	"LASTPASS": 0,
}

func (x ChangeRequest_Manager) String() string {
	return proto.EnumName(ChangeRequest_Manager_name, int32(x))
}
func (ChangeRequest_Manager) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type Status_Type int32

const (
	Status_JOB_START   Status_Type = 0
	Status_TASK_START  Status_Type = 1
	Status_TASK_ERROR  Status_Type = 2
	Status_TASK_FINISH Status_Type = 3
	Status_JOB_FINISH  Status_Type = 4
)

var Status_Type_name = map[int32]string{
	0: "JOB_START",
	1: "TASK_START",
	2: "TASK_ERROR",
	3: "TASK_FINISH",
	4: "JOB_FINISH",
}
var Status_Type_value = map[string]int32{
	"JOB_START":   0,
	"TASK_START":  1,
	"TASK_ERROR":  2,
	"TASK_FINISH": 3,
	"JOB_FINISH":  4,
}

func (x Status_Type) String() string {
	return proto.EnumName(Status_Type_name, int32(x))
}
func (Status_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type ManagersRequest struct {
}

func (m *ManagersRequest) Reset()                    { *m = ManagersRequest{} }
func (m *ManagersRequest) String() string            { return proto.CompactTextString(m) }
func (*ManagersRequest) ProtoMessage()               {}
func (*ManagersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ManagersReply struct {
	Managers []string `protobuf:"bytes,1,rep,name=managers" json:"managers,omitempty"`
}

func (m *ManagersReply) Reset()                    { *m = ManagersReply{} }
func (m *ManagersReply) String() string            { return proto.CompactTextString(m) }
func (*ManagersReply) ProtoMessage()               {}
func (*ManagersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ManagersReply) GetManagers() []string {
	if m != nil {
		return m.Managers
	}
	return nil
}

type PasswdConfig struct {
	Length       uint32 `protobuf:"varint,1,opt,name=length" json:"length,omitempty"`
	Numbers      bool   `protobuf:"varint,2,opt,name=numbers" json:"numbers,omitempty"`
	SpecialChars bool   `protobuf:"varint,3,opt,name=specialChars" json:"specialChars,omitempty"`
}

func (m *PasswdConfig) Reset()                    { *m = PasswdConfig{} }
func (m *PasswdConfig) String() string            { return proto.CompactTextString(m) }
func (*PasswdConfig) ProtoMessage()               {}
func (*PasswdConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PasswdConfig) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *PasswdConfig) GetNumbers() bool {
	if m != nil {
		return m.Numbers
	}
	return false
}

func (m *PasswdConfig) GetSpecialChars() bool {
	if m != nil {
		return m.SpecialChars
	}
	return false
}

// The request message containing the user's name.
type ChangeRequest struct {
	Manager      ChangeRequest_Manager `protobuf:"varint,1,opt,name=manager,enum=changer.ChangeRequest_Manager" json:"manager,omitempty"`
	Email        string                `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password     string                `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	PasswdConfig *PasswdConfig         `protobuf:"bytes,4,opt,name=passwdConfig" json:"passwdConfig,omitempty"`
}

func (m *ChangeRequest) Reset()                    { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()               {}
func (*ChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ChangeRequest) GetManager() ChangeRequest_Manager {
	if m != nil {
		return m.Manager
	}
	return ChangeRequest_LASTPASS
}

func (m *ChangeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChangeRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ChangeRequest) GetPasswdConfig() *PasswdConfig {
	if m != nil {
		return m.PasswdConfig
	}
	return nil
}

// Status interface
// Start status
// Job start status (with subJob ID)
// Job Error status
// Job finish status
// Finish status
type Status struct {
	Type     Status_Type `protobuf:"varint,1,opt,name=type,enum=changer.Status_Type" json:"type,omitempty"`
	JobId    uint64      `protobuf:"varint,2,opt,name=jobId" json:"jobId,omitempty"`
	TaskId   uint64      `protobuf:"varint,3,opt,name=taskId" json:"taskId,omitempty"`
	Hostname string      `protobuf:"bytes,4,opt,name=hostname" json:"hostname,omitempty"`
	Email    string      `protobuf:"bytes,5,opt,name=email" json:"email,omitempty"`
	Msg      string      `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Status) GetType() Status_Type {
	if m != nil {
		return m.Type
	}
	return Status_JOB_START
}

func (m *Status) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *Status) GetTaskId() uint64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Status) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Status) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ManagersRequest)(nil), "changer.ManagersRequest")
	proto.RegisterType((*ManagersReply)(nil), "changer.ManagersReply")
	proto.RegisterType((*PasswdConfig)(nil), "changer.PasswdConfig")
	proto.RegisterType((*ChangeRequest)(nil), "changer.ChangeRequest")
	proto.RegisterType((*Status)(nil), "changer.Status")
	proto.RegisterEnum("changer.ChangeRequest_Manager", ChangeRequest_Manager_name, ChangeRequest_Manager_value)
	proto.RegisterEnum("changer.Status_Type", Status_Type_name, Status_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Changer service

type ChangerClient interface {
	// Sends a greeting
	ChangePassword(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (Changer_ChangePasswordClient, error)
	GetManagers(ctx context.Context, in *ManagersRequest, opts ...grpc.CallOption) (*ManagersReply, error)
}

type changerClient struct {
	cc *grpc.ClientConn
}

func NewChangerClient(cc *grpc.ClientConn) ChangerClient {
	return &changerClient{cc}
}

func (c *changerClient) ChangePassword(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (Changer_ChangePasswordClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Changer_serviceDesc.Streams[0], c.cc, "/changer.Changer/ChangePassword", opts...)
	if err != nil {
		return nil, err
	}
	x := &changerChangePasswordClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Changer_ChangePasswordClient interface {
	Recv() (*Status, error)
	grpc.ClientStream
}

type changerChangePasswordClient struct {
	grpc.ClientStream
}

func (x *changerChangePasswordClient) Recv() (*Status, error) {
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *changerClient) GetManagers(ctx context.Context, in *ManagersRequest, opts ...grpc.CallOption) (*ManagersReply, error) {
	out := new(ManagersReply)
	err := grpc.Invoke(ctx, "/changer.Changer/GetManagers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Changer service

type ChangerServer interface {
	// Sends a greeting
	ChangePassword(*ChangeRequest, Changer_ChangePasswordServer) error
	GetManagers(context.Context, *ManagersRequest) (*ManagersReply, error)
}

func RegisterChangerServer(s *grpc.Server, srv ChangerServer) {
	s.RegisterService(&_Changer_serviceDesc, srv)
}

func _Changer_ChangePassword_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChangerServer).ChangePassword(m, &changerChangePasswordServer{stream})
}

type Changer_ChangePasswordServer interface {
	Send(*Status) error
	grpc.ServerStream
}

type changerChangePasswordServer struct {
	grpc.ServerStream
}

func (x *changerChangePasswordServer) Send(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func _Changer_GetManagers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangerServer).GetManagers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/changer.Changer/GetManagers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangerServer).GetManagers(ctx, req.(*ManagersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Changer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "changer.Changer",
	HandlerType: (*ChangerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManagers",
			Handler:    _Changer_GetManagers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChangePassword",
			Handler:       _Changer_ChangePassword_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "changer.proto",
}

func init() { proto.RegisterFile("changer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcb, 0x8e, 0xda, 0x30,
	0x14, 0x86, 0xf1, 0x90, 0x21, 0xe4, 0x40, 0x20, 0xb5, 0xa6, 0x34, 0x62, 0x51, 0x21, 0xaf, 0x22,
	0x55, 0x42, 0x15, 0xdd, 0xb4, 0x8b, 0x2e, 0x52, 0xd4, 0x0b, 0xbd, 0x0d, 0x72, 0xa2, 0x6e, 0x2b,
	0x33, 0xb8, 0x81, 0x36, 0xb7, 0xc6, 0x46, 0x15, 0xcf, 0xd0, 0x87, 0xeb, 0x0b, 0x75, 0x31, 0xb2,
	0xe3, 0x64, 0x60, 0x34, 0x3b, 0x7f, 0xc7, 0x27, 0x3e, 0xff, 0xff, 0xdb, 0x01, 0xf7, 0x66, 0xc7,
	0xf2, 0x84, 0x57, 0xf3, 0xb2, 0x2a, 0x64, 0x81, 0x6d, 0x83, 0xe4, 0x11, 0x8c, 0xbf, 0xb0, 0x9c,
	0x25, 0xbc, 0x12, 0x94, 0xff, 0x3e, 0x70, 0x21, 0xc9, 0x33, 0x70, 0xef, 0x4a, 0x65, 0x7a, 0xc4,
	0x53, 0xe8, 0x67, 0xa6, 0xe0, 0xa3, 0x59, 0x37, 0x70, 0x68, 0xcb, 0x64, 0x0b, 0xc3, 0x35, 0x13,
	0xe2, 0xcf, 0x76, 0x59, 0xe4, 0x3f, 0xf6, 0x09, 0x9e, 0x40, 0x2f, 0xe5, 0x79, 0x22, 0x77, 0x3e,
	0x9a, 0xa1, 0xc0, 0xa5, 0x86, 0xb0, 0x0f, 0x76, 0x7e, 0xc8, 0x36, 0xea, 0x88, 0x8b, 0x19, 0x0a,
	0xfa, 0xb4, 0x41, 0x4c, 0x60, 0x28, 0x4a, 0x7e, 0xb3, 0x67, 0xe9, 0x72, 0xc7, 0x2a, 0xe1, 0x77,
	0xf5, 0xf6, 0x59, 0x8d, 0xfc, 0x43, 0xe0, 0x2e, 0xb5, 0x62, 0x23, 0x12, 0xbf, 0x04, 0xdb, 0x68,
	0xd0, 0x83, 0x46, 0x8b, 0xa7, 0xf3, 0xc6, 0xe1, 0x59, 0xe3, 0xdc, 0x58, 0xa1, 0x4d, 0x3b, 0xbe,
	0x82, 0x4b, 0x9e, 0xb1, 0x7d, 0xaa, 0x75, 0x38, 0xb4, 0x06, 0xe5, 0xb1, 0x54, 0x3e, 0x8a, 0x6a,
	0xab, 0x15, 0x38, 0xb4, 0x65, 0xfc, 0x0a, 0x86, 0xe5, 0x89, 0x47, 0xdf, 0x9a, 0xa1, 0x60, 0xb0,
	0x78, 0xdc, 0x0e, 0x3c, 0x0d, 0x80, 0x9e, 0xb5, 0x92, 0x27, 0x60, 0x1b, 0x01, 0x78, 0x08, 0xfd,
	0xcf, 0x61, 0x14, 0xaf, 0xc3, 0x28, 0xf2, 0x3a, 0xe4, 0x3f, 0x82, 0x5e, 0x24, 0x99, 0x3c, 0x08,
	0x1c, 0x80, 0x25, 0x8f, 0x25, 0x37, 0x3e, 0xae, 0xda, 0x63, 0xeb, 0xed, 0x79, 0x7c, 0x2c, 0x39,
	0xd5, 0x1d, 0x4a, 0xfa, 0xcf, 0x62, 0xb3, 0xda, 0x6a, 0xe9, 0x16, 0xad, 0x41, 0x45, 0x2e, 0x99,
	0xf8, 0xb5, 0xaa, 0x85, 0x5b, 0xd4, 0x90, 0xb2, 0xb4, 0x2b, 0x84, 0xcc, 0x59, 0xc6, 0xb5, 0x64,
	0x87, 0xb6, 0x7c, 0x17, 0xc2, 0xe5, 0x69, 0x08, 0x1e, 0x74, 0x33, 0x91, 0xf8, 0x3d, 0x5d, 0x53,
	0x4b, 0xf2, 0x0d, 0x2c, 0x35, 0x1f, 0xbb, 0xe0, 0x7c, 0xbc, 0x7e, 0xf3, 0x3d, 0x8a, 0x43, 0x1a,
	0x7b, 0x1d, 0x3c, 0x02, 0x88, 0xc3, 0xe8, 0x93, 0x61, 0xd4, 0xf2, 0x5b, 0x4a, 0xaf, 0xa9, 0x77,
	0x81, 0xc7, 0x30, 0xd0, 0xfc, 0x6e, 0xf5, 0x75, 0x15, 0x7d, 0xf0, 0xba, 0xaa, 0x41, 0x7d, 0x6f,
	0xd8, 0x5a, 0xfc, 0x45, 0x60, 0xd7, 0xf7, 0x54, 0xe1, 0xd7, 0x30, 0xaa, 0x97, 0xeb, 0x26, 0xf0,
	0xc9, 0xc3, 0x77, 0x39, 0x1d, 0xdf, 0xcb, 0x86, 0x74, 0x9e, 0x23, 0x1c, 0xc2, 0xe0, 0x3d, 0x97,
	0xcd, 0x8b, 0xc5, 0x7e, 0xdb, 0x73, 0xef, 0x5d, 0x4f, 0x27, 0x0f, 0xec, 0x94, 0xe9, 0x91, 0x74,
	0x36, 0x3d, 0xfd, 0x53, 0xbc, 0xb8, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x91, 0x3b, 0x19, 0x9c, 0x25,
	0x03, 0x00, 0x00,
}
